declare module "qs";
declare module "nprogress";
declare module "js-md5";
declare module "js-cookie";
declare module "ahooks";
declare module "react-intl";
declare module "react-transition-group";
declare module "vite-plugin-eslint";
declare module "vite-plugin-imagemin";
